apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-feature-demo-jaeger-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-feature-demo-jaeger
  template:
    metadata:
      labels:
        app: open-feature-demo-jaeger
    spec:
      containers:
        - name: open-feature-demo-jaeger
          image: thomaspoignant/go-feature-flag-relay-proxy:v0.3.0
          ports:
            - containerPort: 6832
            - containerPort: 16686
---
apiVersion: v1
kind: Service
metadata:
  name: open-feature-demo-jaeger-service
spec:
  type: NodePort
  selector:
    app: open-feature-demo-jaeger
  ports:
    - port: 6832
      targetPort: 6832
      name: internal
    - port: 16686
      targetPort: 16686
      name: external